name: print github context event
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run: echo "${{toJSON(github.event)}}"